import LeftBar from "@/components/diary/LeftBar";
import MobileLeftBar from "@/components/diary/MobileLeftBar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "My Diary",
  description: "Generated by create next app",
};

export default function MyDiaryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-row">
      <div className="hidden lg:block lg:fixed left-2 top-0 bottom-0">
        <div className="flex space-x-2 group">
          <LeftBar />
          <div className="border-l border-gray-400 h-screen" />
        </div>
      </div>
      <MobileLeftBar />
      <div className="lg:ml-72 flex items-center justify-center w-screen lg:w-full relative">
        {children}
      </div>
    </div>
  );
}
