create table "public"."diarry_entries_moods" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "diary_entry_id" bigint not null,
    "mood_id" bigint not null
);


alter table "public"."diarry_entries_moods" enable row level security;

create table "public"."moods" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."moods" enable row level security;

CREATE UNIQUE INDEX diarry_entries_moods_pkey ON public.diarry_entries_moods USING btree (id);

CREATE UNIQUE INDEX moods_name_key ON public.moods USING btree (name);

CREATE UNIQUE INDEX moods_pkey ON public.moods USING btree (id);

alter table "public"."diarry_entries_moods" add constraint "diarry_entries_moods_pkey" PRIMARY KEY using index "diarry_entries_moods_pkey";

alter table "public"."moods" add constraint "moods_pkey" PRIMARY KEY using index "moods_pkey";

alter table "public"."diarry_entries_moods" add constraint "public_diarry_entries_moods_diary_entry_id_fkey" FOREIGN KEY (diary_entry_id) REFERENCES diary_entries(id) ON DELETE CASCADE not valid;

alter table "public"."diarry_entries_moods" validate constraint "public_diarry_entries_moods_diary_entry_id_fkey";

alter table "public"."diarry_entries_moods" add constraint "public_diarry_entries_moods_mood_id_fkey" FOREIGN KEY (mood_id) REFERENCES moods(id) ON DELETE CASCADE not valid;

alter table "public"."diarry_entries_moods" validate constraint "public_diarry_entries_moods_mood_id_fkey";

alter table "public"."moods" add constraint "moods_name_key" UNIQUE using index "moods_name_key";

grant delete on table "public"."diarry_entries_moods" to "anon";

grant insert on table "public"."diarry_entries_moods" to "anon";

grant references on table "public"."diarry_entries_moods" to "anon";

grant select on table "public"."diarry_entries_moods" to "anon";

grant trigger on table "public"."diarry_entries_moods" to "anon";

grant truncate on table "public"."diarry_entries_moods" to "anon";

grant update on table "public"."diarry_entries_moods" to "anon";

grant delete on table "public"."diarry_entries_moods" to "authenticated";

grant insert on table "public"."diarry_entries_moods" to "authenticated";

grant references on table "public"."diarry_entries_moods" to "authenticated";

grant select on table "public"."diarry_entries_moods" to "authenticated";

grant trigger on table "public"."diarry_entries_moods" to "authenticated";

grant truncate on table "public"."diarry_entries_moods" to "authenticated";

grant update on table "public"."diarry_entries_moods" to "authenticated";

grant delete on table "public"."diarry_entries_moods" to "service_role";

grant insert on table "public"."diarry_entries_moods" to "service_role";

grant references on table "public"."diarry_entries_moods" to "service_role";

grant select on table "public"."diarry_entries_moods" to "service_role";

grant trigger on table "public"."diarry_entries_moods" to "service_role";

grant truncate on table "public"."diarry_entries_moods" to "service_role";

grant update on table "public"."diarry_entries_moods" to "service_role";

grant delete on table "public"."moods" to "anon";

grant insert on table "public"."moods" to "anon";

grant references on table "public"."moods" to "anon";

grant select on table "public"."moods" to "anon";

grant trigger on table "public"."moods" to "anon";

grant truncate on table "public"."moods" to "anon";

grant update on table "public"."moods" to "anon";

grant delete on table "public"."moods" to "authenticated";

grant insert on table "public"."moods" to "authenticated";

grant references on table "public"."moods" to "authenticated";

grant select on table "public"."moods" to "authenticated";

grant trigger on table "public"."moods" to "authenticated";

grant truncate on table "public"."moods" to "authenticated";

grant update on table "public"."moods" to "authenticated";

grant delete on table "public"."moods" to "service_role";

grant insert on table "public"."moods" to "service_role";

grant references on table "public"."moods" to "service_role";

grant select on table "public"."moods" to "service_role";

grant trigger on table "public"."moods" to "service_role";

grant truncate on table "public"."moods" to "service_role";

grant update on table "public"."moods" to "service_role";



